export const motorAbbreviationToNameMap = {
    "RFC": "rightFrontCoxia",
    "RFF": "rightFrontFemur",
    "RFT": "rightFrontTibia",
    "RMC": "rightMiddleCoxia",
    "RMF": "rightMiddleFemur",
    "RMT": "rightMiddleTibia",
    "RBC": "rightBackCoxia",
    "RBF": "rightBackFemur",
    "RBT": "rightBackTibia",
    "LFC": "leftFrontCoxia",
    "LFF": "leftFrontFemur",
    "LFT": "leftFrontTibia",
    "LMC": "leftMiddleCoxia",
    "LMF": "leftMiddleFemur",
    "LMT": "leftMiddleTibia",
    "LBC": "leftBackCoxia",
    "LBF": "leftBackFemur",
    "LBT": "leftBackTibia",
};
